server:
  port: ${NOTIFICATION_SERVICE_PORT:8082}

spring:
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:joaopedroafluz}
    password: ${RABBIT_MQ_PASSWORD:docker}
    listener:
      simple:
        observation-enabled: true
        retry:
          enabled: true
          initial-interval: 2000
          multiplier: 2
          max-attempts: 3
        default-requeue-rejected: false

rabbit:
  exchange: ${RABBIT_MQ_EXCHANGE:pet.exchange}
  adopted:
    queue: pet.adopted.notification
    routing-key: pet.adopted
  registered:
    queue: pet.registered.notification
    routing-key: pet.registered
  deleted:
    queue: pet.deleted.notification
    routing-key: pet.deleted

notification:
  admin-email: ${NOTIFICATION_ADMIN_EMAIL:admin@adoption.com.br}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: notification-service
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
