server:
  port: 8081

spring:
  datasource:
    url: ${PET_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/petservicedb}
    username: ${PET_SERVICE_DB_USERNAME:joaopedroafluz}
    password: ${PET_SERVICE_DB_PASSWORD:docker}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:database/migration
    baseline-on-migrate: true
  application:
    name: pet-service
  cloud:
    discovery:
      enabled: true
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:joaopedroafluz}
    password: ${RABBIT_MQ_PASSWORD:docker}

rabbit:
  queue: ${RABBIT_MQ_QUEUE:pet.adoption.notification}
  exchange: ${RABBIT_MQ_EXCHANGE:pet.exchange}
  routing-key: ${RABBIT_MQ_ROUTING_KEY:pet.adopted}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true