server:
  port: 8081

spring:
  datasource:
    url: ${PET_SERVICE_DB_URL}
    username: ${PET_SERVICE_DB_USERNAME}
    password: ${PET_SERVICE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:database/migration
    baseline-on-migrate: true
  application:
    name: pet-service
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true