services:
  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - adoption-network

  mailhog:
    image: mailhog/mailhog:v1.0.1
    platform: linux/amd64
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - adoption-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - adoption-network

  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mailhog
    networks:
      - adoption-network

  pet-db:
    image: postgres:14.17
    container_name: pet-db
    environment:
      - POSTGRES_USER=${PET_SERVICE_DB_USERNAME}
      - POSTGRES_PASSWORD=${PET_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${PET_SERVICE_DB}
    ports:
      - "5432:5432"
    networks:
      - adoption-network
    volumes:
      - pet-db-data:/var/lib/postgresql/data

  pet-service:
    container_name: pet-service
    build:
      context: ./pet-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - eureka-server
      - pet-db
      - rabbitmq
      - notification-service
    networks:
      - adoption-network

  user-db:
    image: postgres:14.17
    container_name: user-db
    environment:
      - POSTGRES_USER=${USER_SERVICE_DB_USERNAME}
      - POSTGRES_PASSWORD=${USER_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${USER_SERVICE_DB}
    ports:
      - "5433:5432"
    networks:
      - adoption-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  user-service:
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - eureka-server
      - user-db
    networks:
      - adoption-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - pet-service
      - user-service
    networks:
      - adoption-network

  prometheus:
    container_name: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
      - pet-service
      - user-service
      - notification-service
      - api-gateway
    networks:
      - adoption-network

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - adoption-network

networks:
  adoption-network:
    driver: bridge

volumes:
  pet-db-data:
  user-db-data:
