services:
  keycloak-db:
    image: postgres:14.17
    container_name: keycloak-db
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USERNAME}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_DB=${KEYCLOAK_DB}
    ports:
      - "5432:5432"
    networks:
      - adoption-network
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    environment:
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_DB_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    command: start-dev
    networks:
      - adoption-network

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - adoption-network

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.1
    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - adoption-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - adoption-network

  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mailhog
    networks:
      - adoption-network

  pet-db:
    image: postgres:14.17
    container_name: pet-db
    environment:
      - POSTGRES_USER=${PET_SERVICE_DB_USERNAME}
      - POSTGRES_PASSWORD=${PET_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${PET_SERVICE_DB}
    ports:
      - "5433:5432"
    networks:
      - adoption-network
    volumes:
      - pet-db-data:/var/lib/postgresql/data

  # This service must run locally to accept requests from localhost and to properly validate Keycloak tokens.
  #  pet-service:
  #    container_name: pet-service
  #    build:
  #      context: ./pet-service
  #      dockerfile: Dockerfile
  #    ports:
  #      - "8081:8081"
  #    env_file:
  #      - .env
  #    depends_on:
  #      - eureka-server
  #      - pet-db
  #      - rabbitmq
  #    networks:
  #      - adoption-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    #      - pet-service
    networks:
      - adoption-network

  prometheus:
    container_name: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - adoption-network

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - adoption-network

networks:
  adoption-network:
    driver: bridge

volumes:
  keycloak-db-data:
  pet-db-data:
