services:
  keycloak-db:
    image: postgres:14.17
    container_name: keycloak-db
    environment:
      - POSTGRES_USER=${KEYCLOAK_DB_USERNAME}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - POSTGRES_DB=${KEYCLOAK_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adoption-network
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0
    ports:
      - "8080:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    environment:
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_DB_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    entrypoint: ["/bin/bash", "/opt/keycloak/start.sh"]
    command: []
    volumes:
      - ./keycloak/animal-adoption-realm.json:/opt/keycloak/data/import/animal-adoption-realm.json
      - ./keycloak/start.sh:/opt/keycloak/start.sh
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - adoption-network

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/localhost/8761'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - adoption-network

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.1
    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - adoption-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adoption-network

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data
    networks:
      - adoption-network

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name: redisinsight
    ports:
      - "8001:8001"
    networks:
      - adoption-network

  notification-service:
    container_name: notification-service
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "8082:8082"
      - "5006:5006"
    env_file:
      - .env
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - adoption-network

  pet-db:
    image: postgres:14.17
    container_name: pet-db
    environment:
      - POSTGRES_USER=${PET_SERVICE_DB_USERNAME}
      - POSTGRES_PASSWORD=${PET_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${PET_SERVICE_DB}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adoption-network
    volumes:
      - pet-db-data:/var/lib/postgresql/data

  pet-service:
    profiles:
      - full
    container_name: pet-service
    build:
      context: .
      dockerfile: pet-service/Dockerfile
    ports:
      - "8081:8081"
      - "5005:5005"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      eureka-server:
        condition: service_healthy
      pet-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - adoption-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - adoption-network

  prometheus:
    container_name: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - adoption-network

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - adoption-network

networks:
  adoption-network:
    driver: bridge

volumes:
  keycloak-db-data:
  redis-data:
  pet-db-data:
