server:
  port: ${API_GATEWAY_PORT:8080}

app:
  auth:
    public-routes:
      - /auth/login
      - /auth/register
    secret: ${JWT_SECRET:74y3kWugDyVFqvEkGQCadDSYWEfqBuTRBAArqoaHfY588tng2ntb3WvvZEUvkfjb}

spring:
  application:
    name: ${API_GATEWAY_NAME:api-gateway}
  cloud:
    gateway:
      routes:
        - id: ${PET_SERVICE_NAME:pet-service}
          uri: lb://${PET_SERVICE_NAME:pet-service}
          predicates:
            - Path=/pets/**
        - id: ${USER_SERVICE_NAME:user-service}
          uri: lb://${USER_SERVICE_NAME:user-service}
          predicates:
            - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}