server:
  port: ${API_GATEWAY_PORT:80}

spring:
  application:
    name: ${API_GATEWAY_NAME:api-gateway}
  cloud:
    gateway:
      routes:
        - id: ${PET_SERVICE_NAME:pet-service}
          uri: lb://${PET_SERVICE_NAME:pet-service}
          predicates:
            - Path=/pets/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}