server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pets/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

