server:
  port: 8080

app:
  auth:
    public-routes:
      - /auth/login
      - /auth/register
    secret: ${JWT_SECRET:74y3kWugDyVFqvEkGQCadDSYWEfqBuTRBAArqoaHfY588tng2ntb3WvvZEUvkfjb}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pets/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}