global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eureka-server:8761' ]

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:80' ]

  - job_name: 'keycloak'
    static_configs:
      - targets: [ 'keycloak:8080' ]
    metrics_path: /metrics

  - job_name: 'pet-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'pet-service:8081' ]