CREATE SEQUENCE users_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;

CREATE TABLE users
(
    id         int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                          NOT NULL,
    email      VARCHAR(255)                          NOT NULL,
    "password" VARCHAR(255)                          NOT NULL,
    "role"     VARCHAR(255)                          NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email)
);