CREATE SEQUENCE pets_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;

CREATE TABLE pets
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name"      VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    breed       VARCHAR(255)                            NOT NULL,
    "size"      VARCHAR(255)                            NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    gender      VARCHAR(255)                            NOT NULL,
    birth_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_pet PRIMARY KEY (id)
);